# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39d51a0b3ec95fe7bb537d2603208f9f3c03a12d12c18b0d150442167b3214e7f5b753925f00f88bf86fbf56697b8b6305ab1724ba0f2b1bb282f2c67020ec4d

test:
  secret_key_base: 7310ff5ecf0807dc99b206bd1bf3fe4eb52d3e61b0dec598560690092966d8c33b57b2092d7c4b7cb5191647ea0c3cd0bc121e4a6b8c6851fb8c2d46e43ac38f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
